name:                real-time-inference
version:             0.1.0.0
github:              "githubuser/real-time-inference"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/real-time-inference#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat

library:
  source-dirs: src
  dependencies:
  - monad-bayes
  - dunai
  - rhine
  - mmorph
  - gloss
  - log-domain
  - rhine-gloss
  - transformers
  - vector
  - containers
  - witch
  - lens
  - linear
  - text
  - megaparsec
  - bytestring
  default-extensions:
    - RankNTypes
    - Arrows
    - ScopedTypeVariables
    - TypeFamilies
    - FlexibleContexts
    - NamedFieldPuns
    - PatternSynonyms
    - LiberalTypeSynonyms
    - DataKinds
    - BlockArguments
    - FlexibleInstances
    - MultiParamTypeClasses
    - ConstraintKinds
    - KindSignatures
    - LambdaCase
    - OverloadedStrings
    - TypeApplications
    - TypeOperators


executables:
  demo:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    dependencies:
    - real-time-inference

